# Generated by Django 5.0.1 on 2026-03-03 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkloadConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_staff_workload', models.IntegerField(default=20)),
                ('default_hod_workload', models.IntegerField(default=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workload_config', to='core.department')),
            ],
            options={
                'db_table': 'workload_config',
            },
        ),
        migrations.CreateModel(
            name='WorkloadAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('hours_assigned', models.FloatField(default=3.0)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_assignments', to='core.department')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_assignments', to='accounts.staff')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_assignments', to='timetable.subject')),
            ],
            options={
                'db_table': 'workload_assignment',
                'indexes': [models.Index(fields=['staff', 'department'], name='workload_as_staff_i_fa544f_idx'), models.Index(fields=['department', 'subject'], name='workload_as_departm_5d7b4e_idx')],
                'unique_together': {('staff', 'subject', 'class_name')},
            },
        ),
    ]
