# Generated by Django 5.0.1 on 2026-03-03 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver_role', models.CharField(choices=[('LAB_INCHARGE', 'Lab Incharge'), ('COMMON_SUBJECT_HEAD', 'Common Subject Head'), ('COLLEGE_ADMIN', 'College Admin')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_given', to=settings.AUTH_USER_MODEL)),
                ('common_timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='timetable.commontimetable')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='core.department')),
            ],
            options={
                'db_table': 'approvals_approval',
            },
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='approvals.approval')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'approvals_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['common_timetable', 'status'], name='approvals_a_common__1850df_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['approved_by', 'status'], name='approvals_a_approve_4e2f5b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approval',
            unique_together={('common_timetable', 'approver_role', 'department')},
        ),
    ]
