# Generated by Django 5.0.1 on 2026-03-04 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_class'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSubjectMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_mappings', to='core.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_mappings', to='timetable.subject')),
            ],
            options={
                'db_table': 'timetable_class_subject_mapping',
                'indexes': [models.Index(fields=['class_instance'], name='timetable_c_class_i_5f1b5d_idx'), models.Index(fields=['subject'], name='timetable_c_subject_ec1a34_idx')],
                'unique_together': {('class_instance', 'subject')},
            },
        ),
    ]
