# Generated by Django 5.0.1 on 2026-03-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_staff_department'),
        ('timetable', '0002_classsubjectmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='accounts.staff'),
        ),
    ]
