# Generated by Django 5.0.1 on 2026-03-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_subject_hours_friday_subject_hours_monday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('PRACTICAL', 'Practical'), ('LAB', 'Lab'), ('TUTORIAL', 'Tutorial'), ('PROJECT', 'Project')], default='THEORY', max_length=20),
        ),
    ]
