# Generated by Django 5.0.1 on 2026-03-05 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_subject_subject_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'timetable_subject_type',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_type',
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_type_old',
            field=models.CharField(blank=True, default='THEORY', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_type_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='timetable.subjecttype'),
        ),
    ]
