# Generated by Django 5.0.1 on 2026-03-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_subjecttype_remove_subject_subject_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='period_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('break', 'Break'), ('lunch', 'Lunch')], default='regular', help_text='Type of period: regular class, break, or lunch', max_length=20),
        ),
    ]
