# Generated by Django 5.0.1 on 2026-03-04 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='department',
        ),
    ]
