# Generated by Django 5.0.1 on 2026-03-04 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_lab_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year')])),
                ('section', models.CharField(choices=[('A', 'Section A'), ('B', 'Section B')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.department')),
            ],
            options={
                'verbose_name_plural': 'Classes',
                'db_table': 'core_class',
                'unique_together': {('department', 'year', 'section')},
            },
        ),
    ]
