# Generated by Django 5.0.1 on 2026-03-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_staff_department'),
        ('core', '0003_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='tutors',
            field=models.ManyToManyField(blank=True, related_name='classes', to='accounts.staff'),
        ),
    ]
