# Generated by Django 5.0.1 on 2026-03-05 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_class_tutors'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='reference_docx',
            field=models.FileField(blank=True, null=True, upload_to='lab_references/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx'])]),
        ),
    ]
