# Generated by Django 5.0.1 on 2026-03-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_lab_reference_docx'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_strength',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
